# account svc k8s 部署文件
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-svc-deployment
spec:
  replicas: 2
  strategy:
    rollingUpdate:  ##由于replicas为3,则整个升级,pod个数在2-4个之间
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  template:
    metadata:
      labels:
        app: gateway-svc
        env: dev
    spec:
      containers:
        - name: gateway-svc
          image: registry.mqcoding.com:5000/micro-demo-gateway-svc:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: micro-config
          env:
            - name: SW_AGENT_NAME
              value: gateway-svc
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: oap-server:11800
            - name: SW_AGENT_SAMPLE
              value: "10"
          volumeMounts:
          - mountPath: /etc/localtime
            name: dateconf
      volumes:
      - name: dateconf
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-svc
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP