# account svc k8s 部署文件
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mail-svc-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mail-svc
        env: dev
    spec:
      containers:
        - name: mail-svc
          image: registry.mqcoding.com:5000/micro-demo-mail-svc:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: micro-config
          env:
            - name: SW_AGENT_NAME
              value: mail-svc
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: oap-server:11800
            - name: SW_AGENT_SAMPLE
              value: "10"
          volumeMounts:
          - mountPath: /etc/localtime
            name: dateconf
      volumes:
      - name: dateconf
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-svc
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80