# account svc k8s 部署文件
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mail-svc-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mail-svc
        env: dev
    spec:
      containers:
        - name: mail-svc
          image: registry.mqcoding.com:5000/micro-demo-mail-svc:latest
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: micro-config
---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-svc
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80