# account svc k8s 部署文件
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-svc-deployment-blue
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: account-svc
        env: dev
        track: blue
    spec:
      containers:
        - name: account-svc
          image: registry.mqcoding.com:5000/micro-demo-account-svc:blue
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: micro-config
          env:
            - name: SW_AGENT_NAME
              value: account-svc
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: oap-server:11800
          volumeMounts:
          - mountPath: /etc/localtime
            name: dateconf
      volumes:
      - name: dateconf
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai