# account svc k8s 部署文件
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-svc-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account-svc
        env: dev
    spec:
      containers:
        - name: account-svc
          image: registry.mqcoding.com:5000/micro-demo-account-svc:latest
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: micro-config
          env:
            - name: SW_AGENT_NAME
              value: account-svc
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-svc
    env: dev
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30033