# application.yml 本地开发环境，是否需要待确认

server:
  port: 8081
micro-demo:
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://localhost:8081}
  bot-service-endpoint: ${BOT_SERVICE_ENDPOINT:http://localhost:8082}