# application.yml

spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: account_route
          uri: lb://${ACCOUNT_SERVICE_NAME}:80
          predicates:
          - Path=/v1/account/**