# 部署到k8s上的配置项
apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-config
data:
  SERVER_PORT: "80"                                         #服务端口
  SPRING_PROFILES_ACTIVE: dev                               #指定在k8s上使用的配置环境
  ACCOUNT_SERVICE_ENDPOINT: http://account-service
  BOT_SERVICE_ENDPOINT: http://bot-service
  MAIL_SERVICE_ENDPOINT: http://mail-service